### ISSUE TITLE
Songwriters doesn't appear on the same line as other navigation items

### ISSUE THREAD

**Issue by joshghent** [maridco/marid-frontend#14]
Affects index.html

**Comment by nb333** [comment]
@naveen09 this issue occurred during one of the recent pull requests. any idea?

**Comment by naveen09** [comment]
@joshghent  Seems to me like containers width issue. I changed the css in my local  as

.container {
    width: 1010px;
}
@line 1321 (stylesheet.css)
it works fine. Shall I push that ?

**Comment by nb333** [comment]
@naveen09 I tried to test that on OS X, unsuccessfully, but push it and I'll see if it works.

**Comment by naveen09** [comment]
@nb333  @joshghent  I also see that footer is not centered ! I fixed that too. I`ll push both.

**Comment by joshghent** [comment]
I didn't really want the footer centered as there is going to be more elements added to it.

**Comment by joshghent** [comment]
Tested on OSX and still not fixed... Ill take a look into this later after I have built the other pages.
